<?php

return [
    ['Ananda Putri Marsilea', 'D2', 'ANGGOTA', 'UNEJ', 'anandaputrimarsilea@mpjember.com', 'anggota123'],
    ['Ahmad Fajar Ramadhani', 'D2', 'ANGGOTA', 'UNEJ', 'ahmadfajarramadhani@mpjember.com', 'anggota123'],
    ['Dewi Nur Haifa', 'D2', 'ANGGOTA', 'UNEJ', 'dewinurhaifa@mpjember.com', 'anggota123'],
    ['Emi Nafisyah', 'D2', 'ANGGOTA', 'UNEJ', 'eminafisyah@mpjember.com', 'anggota123'],
    ['Muhammad Rio', 'D1', 'ANGGOTA', 'UNEJ', 'muhammadrio@mpjember.com', 'anggota123'],
    ['Muhammad Sandy Satrio Utama', 'D2', 'ANGGOTA', 'POLIJE', 'muhammadsandysatrioutama@mpjember.com', 'anggota123'],
    ['Dhani Mas Ahmad Ilyasa', 'D2', 'ANGGOTA', 'POLIJE', 'dhanimasahmadilyasa@mpjember.com', 'anggota123'],
    ['Winda Ayu Putri Agustin', 'D1', 'ANGGOTA', 'POLIJE', 'windayaputriagustin@mpjember.com', 'anggota123'],
    ['Aldyo Baharudin Windy A.', 'D1', 'ANGGOTA', 'POLIJE', 'aldyobaharudinwindya@mpjember.com', 'anggota123'],
    ['Gabriella Vandista', 'D2', 'ANGGOTA', 'TEGAL BESAR', 'gabriellavandista@mpjember.com', 'anggota123'],
    ['Naomi Yulanda P.', 'D2', 'ANGGOTA', 'TEGAL BESAR', 'naomiyulandap@mpjember.com', 'anggota123'],
    ['Arumi', 'D2', 'ANGGOTA', 'TEGAL BESAR', 'arumi@mpjember.com', 'anggota123'],
    ['Ayumi Yulanda P.', 'D2', 'ANGGOTA', 'TEGAL BESAR', 'ayumiyulandap@mpjember.com', 'anggota123'],
    ['Lili', 'D2', 'ANGGOTA', 'TEGAL BESAR', 'lili@mpjember.com', 'anggota123'],
    ['Nayla Shafa Alzaena', 'D2', 'ANGGOTA', 'TEGAL BESAR', 'naylashafaalzaena@mpjember.com', 'anggota123'],
    ['Ibrahim Nazril Ghozali', 'D2', 'ANGGOTA', 'TEGAL BESAR', 'ibrahimnazrilghozali@mpjember.com', 'anggota123'],
    ['Abrisamziyad Ghozali', 'D2', 'ANGGOTA', 'TEGAL BESAR', 'abrisamziyadghozali@mpjember.com', 'anggota123'],
    ['Muhammad Fiqri Ghozali', 'D2', 'ANGGOTA', 'TEGAL BESAR', 'muhammadfiqrigozali@mpjember.com', 'anggota123'],
    ['Stanly', 'D2', 'ANGGOTA', 'TEGAL BESAR', 'stanly@mpjember.com', 'anggota123'],
    ['Raditya Ridwan', 'CA', 'ANGGOTA', 'TEGAL BESAR', 'radityaridwan@mpjember.com', 'anggota123'],
    ['Saka', 'CA', 'ANGGOTA', 'TEGAL BESAR', 'saka@mpjember.com', 'anggota123'],
    ['Hariel Egan Wicaksono', 'D2', 'ANGGOTA', 'PONDOK GEDE', 'harieleganwicaksono@mpjember.com', 'anggota123'],
    ['Fajar', 'D1', 'ANGGOTA', 'PONDOK GEDE', 'fajar@mpjember.com', 'anggota123'],
    ['M. Raihan Ibrahim', 'D1', 'ANGGOTA', 'PONDOK GEDE', 'm.raihanibrahim@mpjember.com', 'anggota123'],
    ['Dimas Lukman Prasetyo', 'B1', 'ANGGOTA', 'KALIGA', 'dimaslukmanprasetyo@mpjember.com', 'anggota123'],
    ['Dzaky Audani', 'B1', 'ANGGOTA', 'KALIGA', 'dzakyaudani@mpjember.com', 'anggota123'],
    ['Fayyadh Alvaro Dhawy H', 'D1', 'ANGGOTA', 'KALIGA', 'fayyadhalvarodhawyh@mpjember.com', 'anggota123'],
    ['Fatih', 'CA', 'ANGGOTA', 'KALIGA', 'fatih@mpjember.com', 'anggota123'],
    ['Kenzie Kaili Kurnia', 'D1', 'ANGGOTA', 'BSG', 'kenziekailikurnia@mpjember.com', 'anggota123'],
    ['Raditya Eka Prasetya', 'D1', 'ANGGOTA', 'BSG', 'radityaekaprasetya@mpjember.com', 'anggota123'],
    ['Moch Nanda Ardiansyah', 'D2', 'ANGGOTA', 'BSG', 'moehnandaardiansyah@mpjember.com', 'anggota123'],
    ['Arlita Najwa', 'D1', 'ANGGOTA', 'BSG', 'arlitanajwa@mpjember.com', 'anggota123'],
    ['Gibra Dafin Prasetya', 'D2', 'ANGGOTA', 'TANGGUL RAYA', 'gibradafinprasetya@mpjember.com', 'anggota123'],
    ['M. Firman Arya', 'D1', 'ANGGOTA', 'TANGGUL RAYA', 'm.firmanarya@mpjember.com', 'anggota123'],
    ['M. Fauzan Fitransyah', 'D2', 'ANGGOTA', 'SMASA', 'm.fauzanfitransyah@mpjember.com', 'anggota123'],
    ['Yusriel Abdi Maulana', 'D2', 'ANGGOTA', 'SMASA', 'yusrielabdimaulana@mpjember.com', 'anggota123'],
    ['Mas Syehi Priyatama S', 'D1', 'ANGGOTA', 'SMASA', 'massyehipriyantamas@mpjember.com', 'anggota123'],
    ['Muhammad Alfiansyah', 'CA', 'ANGGOTA', 'SMASA', 'muhammadalfiansyah@mpjember.com', 'anggota123'],
    ['Fina Nailul Ihza', 'D2', 'ANGGOTA', 'SMK 6', 'finanailulihza@mpjember.com', 'anggota123'],
    ['Nur Anna Altafunnia', 'D2', 'ANGGOTA', 'SMK 6', 'nurannaaltafunnia@mpjember.com', 'anggota123'],
    ['Nur Thalita Syafa', 'D2', 'ANGGOTA', 'SMK 6', 'nurthalitasyafa@mpjember.com', 'anggota123'],
    ['Aulia Rizqi Widya P', 'D2', 'ANGGOTA', 'MATASA', 'auliarizqiwidyap@mpjember.com', 'anggota123'],
    ['Ucik Azzara Arianti', 'D2', 'ANGGOTA', 'MATASA', 'ucikazzaraarianti@mpjember.com', 'anggota123'],
    ['Akhmad Bara Al Hafidz', 'D2', 'ANGGOTA', 'MATASA', 'akhmadbaraalhafidz@mpjember.com', 'anggota123'],
    ['Sajjad Abdullah Sabda', 'D2', 'ANGGOTA', 'MATASA', 'sajjadabdullahsabda@mpjember.com', 'anggota123'],
    ['M. Zaki Adwa Pratama', 'D2', 'ANGGOTA', 'MATASA', 'm.zakiadwapratama@mpjember.com', 'anggota123'],
    ['Izzah Aulia Putri', 'D2', 'ANGGOTA', 'MATASA', 'izzahauliaputri@mpjember.com', 'anggota123'],
    ['Kendra Nindi Aulia Hanum', 'D2', 'ANGGOTA', 'MATASA', 'kendranindiauliahanum@mpjember.com', 'anggota123'],
    ['Aura Putri Nasya Zahira', 'D2', 'ANGGOTA', 'MATASA', 'auraputrinasyazahira@mpjember.com', 'anggota123'],
    ['Aura Putri Nesya Zahira', 'D2', 'ANGGOTA', 'MATASA', 'auraputrinesyazahira@mpjember.com', 'anggota123'],
    ['Rasya Adyatama', 'D1', 'ANGGOTA', 'MATASA', 'rasyaadyatama@mpjember.com', 'anggota123'],
    ['Ahmad Rafi Hibatullah', 'CA', 'ANGGOTA', 'MATASA', 'ahmadrafihibatullah@mpjember.com', 'anggota123'],
    ['Filza Hafiizah Hariyadi', 'D2', 'ANGGOTA', 'ROLASI', 'filzahafiizahhariyadi@mpjember.com', 'anggota123'],
    ['Fitri Dwi Ainur Rochma', 'D2', 'ANGGOTA', 'ROLASI', 'fitridwiainurrochma@mpjember.com', 'anggota123'],
    ['Early Syawalia Dewi Palupi', 'D2', 'ANGGOTA', 'ROLASI', 'earlysyawaliadewipalupi@mpjember.com', 'anggota123'],
    ['Vaizah Juliyana Putri', 'D2', 'ANGGOTA', 'ROLASI', 'vaizahjuliyanaputri@mpjember.com', 'anggota123'],
    ['Kirana Aulia', 'D2', 'ANGGOTA', 'ROLASI', 'kiranaaulia@mpjember.com', 'anggota123'],
    ['Arsalu Alifia', 'D2', 'ANGGOTA', 'ROLASI', 'arsalualifia@mpjember.com', 'anggota123'],
    ['Iin Agustin', 'D2', 'ANGGOTA', 'ROLASI', 'iinagustin@mpjember.com', 'anggota123'],
    ['Salsabila Nadifa Aqila', 'D2', 'ANGGOTA', 'ROLASI', 'salsabilanadifaaqila@mpjember.com', 'anggota123'],
    ['Bahrul Ilmi', 'D2', 'ANGGOTA', 'ROLASI', 'bahrulilmi@mpjember.com', 'anggota123'],
    ['Oktaviano Putra Wicaksono', 'D1', 'ANGGOTA', 'ROLASI', 'oktavianoputrawicaksono@mpjember.com', 'anggota123'],
    ['Sapta Jayadi', 'D1', 'ANGGOTA', 'ROLASI', 'saptajayadi@mpjember.com', 'anggota123'],
    ['Zakaria Septihaqq Bayu Aji', 'D1', 'ANGGOTA', 'ROLASI', 'zakariaseptihaqqbayuaji@mpjember.com', 'anggota123'],
    ['Amelia Fitri Maharani', 'D1', 'ANGGOTA', 'ROLASI', 'ameliafitrimaharani@mpjember.com', 'anggota123'],
    ['Rama Michael HJ', 'D2', 'ANGGOTA', 'SUMSAGA', 'ramamichaelhj@mpjember.com', 'anggota123'],
    ['M. Robert Wibisono', 'D2', 'ANGGOTA', 'SUMSAGA', 'm.robertwibisono@mpjember.com', 'anggota123'],
    ['Zahfira Wilis Nanda', 'D2', 'ANGGOTA', 'SUMSAGA', 'zahfirawilisnanda@mpjember.com', 'anggota123'],
    ['Nimas Eva Pramudita', 'D1', 'ANGGOTA', 'SUMSAGA', 'nimasevapramudita@mpjember.com', 'anggota123'],
    ['M. Ibrahim Al Fatih', 'D1', 'ANGGOTA', 'SUMSAGA', 'm.ibrahimalfatih@mpjember.com', 'anggota123'],
    ['Satria Almukti Syius', 'D1', 'ANGGOTA', 'SUMSAGA', 'satriaalmuktisyius@mpjember.com', 'anggota123'],
    ['Jefri Bima B', 'D2', 'ANGGOTA', 'TANGGUL WETAN', 'jefribimab@mpjember.com', 'anggota123'],
    ['Lady Trilaya Azzuria', 'D2', 'ANGGOTA', 'TANGGUL WETAN', 'ladytrilayaazzuria@mpjember.com', 'anggota123'],
    ['Dinda Ridwansyah', 'D2', 'ANGGOTA', 'TANGGUL WETAN', 'dindaridwansyah@mpjember.com', 'anggota123'],
    ['Mohammad Abil Maulana Z.', 'D1', 'ANGGOTA', 'TANGGUL WETAN', 'mohammadabilmaulanaz@mpjember.com', 'anggota123'],
    ['Asrof Hadi Maulana', 'CA', 'ANGGOTA', 'TANGGUL WETAN', 'asrofhadimaulana@mpjember.com', 'anggota123'],
    ['Mila Hindrayani', 'B1', 'ANGGOTA', 'B1-B2', 'milahindrayani@mpjember.com', 'anggota123'],
    ['Dewi Siti Mukaromah', 'B1', 'ANGGOTA', 'B1-B2', 'dewisitimukaromah@mpjember.com', 'anggota123'],
    ['Inka Nur A.', 'B1', 'ANGGOTA', 'B1-B2', 'inkanura@mpjember.com', 'anggota123'],
    ['Aiziz Zahro', 'B1', 'ANGGOTA', 'B1-B2', 'aizizzahro@mpjember.com', 'anggota123'],
    ['Safira Nuzul R.', 'B1', 'ANGGOTA', 'B1-B2', 'safiranuzulr@mpjember.com', 'anggota123'],
    ['Yeni Dwi A.', 'B1', 'ANGGOTA', 'B1-B2', 'yenidwia@mpjember.com', 'anggota123'],
    ['Zalsa Oktavia R.', 'B1', 'ANGGOTA', 'B1-B2', 'zalsaoktavir@mpjember.com', 'anggota123'],
    ['Siti Afiah D.', 'B1', 'ANGGOTA', 'B1-B2', 'sitiafiahd@mpjember.com', 'anggota123'],
    ['Nayaka Al Fachri', 'B1', 'ANGGOTA', 'B1-B2', 'nayakaalfachri@mpjember.com', 'anggota123'],
    ['Revinando Elian', 'B1', 'ANGGOTA', 'B1-B2', 'revinandoelian@mpjember.com', 'anggota123'],
    ['Abel Muyassar Rizqullah', 'B1', 'ANGGOTA', 'B1-B2', 'abelmuyassarrizqullah@mpjember.com', 'anggota123'],
    ['Iqbal Al Mustaghfiriina', 'B1', 'ANGGOTA', 'B1-B2', 'iqbalalmustaghfiriina@mpjember.com', 'anggota123'],
    ['Sinta Dwi Septian', 'B1', 'ANGGOTA', 'B1-B2', 'sintadwiseptian@mpjember.com', 'anggota123'],
    ['M. Farel Agustian', 'B1', 'ANGGOTA', 'B1-B2', 'm.farelagustian@mpjember.com', 'anggota123'],
    ['Nuril Izza Najmal Jamil', 'B1', 'ANGGOTA', 'B1-B2', 'nurilizzanajmaljamil@mpjember.com', 'anggota123'],
    ['Zhafran Kurnia', 'B1', 'ANGGOTA', 'B1-B2', 'zhafrankurnia@mpjember.com', 'anggota123'],
    ['Aliffandra Nur Firdauzi', 'B1', 'ANGGOTA', 'B1-B2', 'aliffandranurfirdauzi@mpjember.com', 'anggota123'],
    ['Abi Julianto', 'B1', 'ANGGOTA', 'B1-B2', 'abijulianto@mpjember.com', 'anggota123'],
    ['Donna Celina Kurniawan', 'B1', 'ANGGOTA', 'B1-B2', 'donnacelinakurniawan@mpjember.com', 'anggota123'],
    ['Nayzilla Fajria Rabbani', 'B1', 'ANGGOTA', 'B1-B2', 'nayzillafajriarabbani@mpjember.com', 'anggota123'],
    ['Nasya Zahira Putri Elya', 'B1', 'ANGGOTA', 'B1-B2', 'nasyazahiraputrielya@mpjember.com', 'anggota123'],
    ['Siti Nurul Khumairoh', 'B1', 'ANGGOTA', 'B1-B2', 'sitinurulkhumairoh@mpjember.com', 'anggota123'],
    ['Farel Rudianto', 'B1', 'ANGGOTA', 'B1-B2', 'farelrudianto@mpjember.com', 'anggota123'],
    ['Aliyya Siti', 'B1', 'ANGGOTA', 'B1-B2', 'aliyyasiti@mpjember.com', 'anggota123'],
    ['Arumi Alexandria', 'B1', 'ANGGOTA', 'B1-B2', 'arumialexandria@mpjember.com', 'anggota123'],
    ['Arifin', 'B1', 'ANGGOTA', 'B1-B2', 'arifin@mpjember.com', 'anggota123'],
    ['Khoiron', 'B2', 'ANGGOTA', 'B1-B2', 'khoiron@mpjember.com', 'anggota123'],
    ['Mita Fitri Y', 'B2', 'ANGGOTA', 'B1-B2', 'mitafitriy@mpjember.com', 'anggota123'],
    ['Andri', 'B2', 'ANGGOTA', 'B1-B2', 'andri@mpjember.com', 'anggota123'],
    ['Aura Ulima', 'B2', 'ANGGOTA', 'B1-B2', 'auraulima@mpjember.com', 'anggota123'],
    ['Rima Ayudya', 'B2', 'ANGGOTA', 'B1-B2', 'rimaayudya@mpjember.com', 'anggota123'],
    ['Septian Arya Bayu Seto', 'B2', 'ANGGOTA', 'B1-B2', 'septianaryabayuseto@mpjember.com', 'anggota123'],
    ['Zanirah', 'B2', 'ANGGOTA', 'B1-B2', 'zanirah@mpjember.com', 'anggota123'],
    ['M. Gigih Restu Arbi', 'B2', 'ANGGOTA', 'B1-B2', 'm.gigihrestuarbi@mpjember.com', 'anggota123'],
    ['Rival Rizki', 'B2', 'ANGGOTA', 'B1-B2', 'rivalrizki@mpjember.com', 'anggota123'],
    ['Gebyar Bintang Tri A', 'B2', 'ANGGOTA', 'B1-B2', 'gebyarbintangtria@mpjember.com', 'anggota123'],
    ['M. Gilang Ramadhany', 'B2', 'ANGGOTA', 'B1-B2', 'm.gilangramadhany@mpjember.com', 'anggota123'],
    ['M. Aril Amrullah', 'B2', 'ANGGOTA', 'B1-B2', 'm.arilamrullah@mpjember.com', 'anggota123'],
    ['M. Alfin Safa\'at', 'B2', 'ANGGOTA', 'B1-B2', 'm.alfinsafaat@mpjember.com', 'anggota123'],
    ['Siti Maimuna', 'B2', 'ANGGOTA', 'B1-B2', 'sitimaimuna@mpjember.com', 'anggota123'],
    ['Honey Anggun Septanti', 'B2', 'ANGGOTA', 'B1-B2', 'honeyanggunseptanti@mpjember.com', 'anggota123'],
    ['M. Fatih Rizqul Husain', 'B2', 'ANGGOTA', 'B1-B2', 'm.fatihrizqulhusain@mpjember.com', 'anggota123'],
    ['M. Virgil Ramadhan', 'B2', 'ANGGOTA', 'B1-B2', 'm.virgilramadhan@mpjember.com', 'anggota123'],
    // Data Pelatih
    ['Siti Maimuna', 'B2', 'PELATIH', 'UNEJ', 'sitimaimuna.pelatih@mpjember.com', 'pelatih123'],
    ['M. Alfin Safa\'at', 'B2', 'PELATIH', 'UNEJ', 'm.alfinsafaat.pelatih@mpjember.com', 'pelatih123'],
    ['Gebyar Bintang Tri A', 'B2', 'PELATIH', 'KALIGA', 'gebyarbintangtria.pelatih@mpjember.com', 'pelatih123'],
    ['Honey Anggun Septanti', 'B2', 'PELATIH', 'SUMSAGA', 'honeyanggunseptanti.pelatih@mpjember.com', 'pelatih123'],
    ['M. Gigih Restu Arbi', 'B2', 'PELATIH', 'PONDOK GEDE', 'm.gigihrestuarbi.pelatih@mpjember.com', 'pelatih123'],
    ['M. Gilang Ramadhany', 'B2', 'PELATIH', 'ROLASI', 'm.gilangramadhany.pelatih@mpjember.com', 'pelatih123'],
    ['M. Aril Amrullah', 'B2', 'PELATIH', 'TANGGUL RAYA', 'm.arilamrullah.pelatih@mpjember.com', 'pelatih123'],
    ['Rival Rizki', 'B2', 'PELATIH', 'TEGAL BESAR', 'rivalrizki.pelatih@mpjember.com', 'pelatih123'],
    ['Rima Ayudya', 'B2', 'PELATIH', 'ARJASA', 'rimaayudya.pelatih@mpjember.com', 'pelatih123'],
    ['Septian Arya Bayu Seto', 'B2', 'PELATIH', 'UNEJ', 'septianaryabayuseto.pelatih@mpjember.com', 'pelatih123'],
    ['Zalsa Oktavia R.', 'B1', 'PELATIH', 'MATASA', 'zalsaoktavir.pelatih@mpjember.com', 'pelatih123'],
    ['Siti Afiah D.', 'B1', 'PELATIH', 'MATASA', 'sitiafiahd.pelatih@mpjember.com', 'pelatih123'],
];
